-- VIU SRM - Actividad 2.1
-- Pioneer follower controller for Bill.
-- The mode is selected with followerControlMode = P|PI|PID|LQR|NMPC.

sim = require('sim')

local cfg = {
    wheelRadius = 0.0975,
    trackWidth = 0.331,
    desiredDistance = 0.82,
    vMax = 0.56,
    vReverseMax = -0.10,
    wMax = 1.65,
    headingKp = 1.70,
    headingKd = 0.04,
    integralLimit = 0.45,
    derivativeAlpha = 0.22,
    logPeriod = 0.80,
    kinematicBase = true,
    robotZ = 0.1388,
    robotMass = 16.5,
    yawInertia = 0.72,
    rollingForce = 2.8,
    wheelViscous = 0.006,
}

local gains = {
    P = {kp = 0.42, ki = 0.00, kd = 0.00},
    PI = {kp = 0.62, ki = 0.140, kd = 0.00},
    PID = {kp = 0.75, ki = 0.100, kd = 0.34},
}

local drive = {
    P = {vMax = 0.50, vReverseMax = -0.20, wMax = 1.35, headingKp = 1.35, headingKd = 0.00, accel = 3.0, brake = 0.22, turnAccel = 2.0, settleError = 0.08},
    PI = {vMax = 0.58, vReverseMax = -0.12, wMax = 1.70, headingKp = 1.70, headingKd = 0.04, accel = 6.0, brake = 5.0, turnAccel = 6.0, settleError = 0.08},
    PID = {vMax = 0.56, vReverseMax = -0.12, wMax = 1.85, headingKp = 1.85, headingKd = 0.08, accel = 7.5, brake = 7.5, turnAccel = 8.0, settleError = 0.045, settleExit = 0.075, derivativeAlpha = 0.22},
    LQR = {vMax = 0.42, vReverseMax = -0.08, wMax = 1.30, headingKp = 1.38, headingKd = 0.20, accel = 1.45, brake = 1.35, turnAccel = 1.55, settleError = 0.055, settleExit = 0.105, derivativeAlpha = 0.055, deadband = 0.014, commandDeadband = 0.004},
    NMPC = {vMax = 0.36, vReverseMax = -0.08, wMax = 0.90, accel = 1.80, brake = 1.70, turnAccel = 1.70, settleError = 0.060, settleExit = 0.11},
}

local nmpcCfg = {
    horizon = 10,
    dt = 0.22,
    iterations = 2,
    stepV = {0.065, 0.025},
    stepW = {0.16, 0.065},
    qDistance = 48.0,
    qTarget = 7.0,
    qHeading = 1.2,
    rV = 1.4,
    rW = 1.8,
    rWheel = 0.020,
    sV = 65.0,
    sW = 18.0,
    terminal = 6.0,
}

local lqrCfg = {
    -- Offline discrete LQR for x=[e_long, e_lat, e_yaw] and u=[delta_v, delta_w].
    -- Generated by compute_follower_lqr_gain.py with dt=0.05, v_ref=0.22 and w_ref=0.22/1.55.
    K = {
        {-2.34963497, 1.29248967, 0.12030307},
        {0.24273764, -4.35704991, -2.68868520},
    },
    q = {35.0, 80.0, 18.0},
    r = {6.0, 3.0},
}

local robot = -1
local bill = -1
local leftMotor = -1
local rightMotor = -1
local mode = 'P'
local integral = 0
local lastError = 0
local lastErrorValid = false
local lastHeading = 0
local lastHeadingValid = false
local filteredDerivative = 0
local actualV = 0
local actualW = 0
local lastPowerV = 0
local lastPowerW = 0
local lastULeft = 0
local lastURight = 0
local energyJ = 0
local settledLatched = false
local lastBillYaw = 0
local lastBillYawValid = false
local filteredBillYawRate = 0
local nmpcInitialized = false
local nmpcSeqV = {}
local nmpcSeqW = {}
local lastT = -1
local lastLogT = -1000
local lastState = ''

local function clamp(value, lo, hi)
    if value < lo then return lo end
    if value > hi then return hi end
    return value
end

local function atan2(y, x)
    if math.atan2 then return math.atan2(y, x) end
    return math.atan(y, x)
end

local function safeGetObject(path)
    local ok, handle = pcall(sim.getObject, path)
    if ok and handle and handle >= 0 then return handle end
    return -1
end

local function readMode()
    local signal = sim.getStringSignal('followerControlMode')
    if signal == 'PI' or signal == 'PID' or signal == 'LQR' or signal == 'NMPC' or signal == 'P' then
        return signal
    end
    return 'P'
end

local function setWheelSpeeds(v, w)
    if cfg.kinematicBase then
        sim.setJointTargetVelocity(leftMotor, 0)
        sim.setJointTargetVelocity(rightMotor, 0)
        return
    end

    local vLeft = (v - 0.5 * cfg.trackWidth * w) / cfg.wheelRadius
    local vRight = (v + 0.5 * cfg.trackWidth * w) / cfg.wheelRadius
    sim.setJointTargetVelocity(leftMotor, vLeft)
    sim.setJointTargetVelocity(rightMotor, vRight)
end

local function firstOrder(current, target, rate, dt)
    local alpha = clamp(rate * dt, 0, 1)
    return current + (target - current) * alpha
end

local function wheelKinematics(v, w)
    local leftLinear = v - 0.5 * cfg.trackWidth * w
    local rightLinear = v + 0.5 * cfg.trackWidth * w
    return leftLinear, rightLinear, leftLinear / cfg.wheelRadius, rightLinear / cfg.wheelRadius
end

local function publishWheelPower(v, w, dt)
    local leftLinear, rightLinear, leftOmega, rightOmega = wheelKinematics(v, w)
    local duLeft = 0
    local duRight = 0
    if dt > 0.000001 then
        duLeft = leftOmega - lastULeft
        duRight = rightOmega - lastURight
    end
    local accel = 0
    local angularAccel = 0
    if dt > 0.000001 then
        accel = (v - lastPowerV) / dt
        angularAccel = (w - lastPowerW) / dt
    end

    local leftPower = math.abs(0.5 * cfg.robotMass * accel * leftLinear)
        + 0.5 * cfg.rollingForce * math.abs(leftLinear)
        + cfg.wheelViscous * leftOmega * leftOmega
    local rightPower = math.abs(0.5 * cfg.robotMass * accel * rightLinear)
        + 0.5 * cfg.rollingForce * math.abs(rightLinear)
        + cfg.wheelViscous * rightOmega * rightOmega
    local yawPower = math.abs(cfg.yawInertia * angularAccel * w)
    local totalPower = leftPower + rightPower + yawPower

    energyJ = energyJ + totalPower * dt
    lastPowerV = v
    lastPowerW = w
    lastULeft = leftOmega
    lastURight = rightOmega

    sim.setFloatSignal('followerWheelLeftLinear', leftLinear)
    sim.setFloatSignal('followerWheelRightLinear', rightLinear)
    sim.setFloatSignal('followerWheelLeftOmega', leftOmega)
    sim.setFloatSignal('followerWheelRightOmega', rightOmega)
    sim.setFloatSignal('followerWheelLeftU', leftOmega)
    sim.setFloatSignal('followerWheelRightU', rightOmega)
    sim.setFloatSignal('followerWheelLeftDeltaU', duLeft)
    sim.setFloatSignal('followerWheelRightDeltaU', duRight)
    sim.setFloatSignal('followerWheelLeftPower', leftPower)
    sim.setFloatSignal('followerWheelRightPower', rightPower)
    sim.setFloatSignal('followerYawPower', yawPower)
    sim.setFloatSignal('followerPowerTotal', totalPower)
    sim.setFloatSignal('followerEnergyJ', energyJ)
end

local function wrapAngle(a)
    while a > math.pi do a = a - 2 * math.pi end
    while a < -math.pi do a = a + 2 * math.pi end
    return a
end

local function integrateKinematicBase(v, w, dt)
    if not cfg.kinematicBase then return end

    local pos = sim.getObjectPosition(robot)
    local ori = sim.getObjectOrientation(robot)
    local yaw = wrapAngle(ori[3] + w * dt)
    local step = v * dt

    pos[1] = pos[1] + step * math.cos(yaw)
    pos[2] = pos[2] + step * math.sin(yaw)
    pos[3] = cfg.robotZ
    sim.setObjectPosition(robot, pos)
    sim.setObjectOrientation(robot, {0, 0, yaw})
    pcall(sim.resetDynamicObject, robot)
end

local function readBillReference(billPos, billYaw, dt)
    local billSpeed = sim.getFloatSignal('billSpeed') or 0
    local yawRate = 0
    if lastBillYawValid and dt > 0.000001 then
        yawRate = clamp(wrapAngle(billYaw - lastBillYaw) / dt, -1.4, 1.4)
    end
    filteredBillYawRate = 0.22 * yawRate + 0.78 * filteredBillYawRate
    lastBillYaw = billYaw
    lastBillYawValid = true

    local c = math.cos(billYaw)
    local s = math.sin(billYaw)
    local targetX = billPos[1] - cfg.desiredDistance * c
    local targetY = billPos[2] - cfg.desiredDistance * s

    local targetVx = billSpeed * c + cfg.desiredDistance * filteredBillYawRate * s
    local targetVy = billSpeed * s - cfg.desiredDistance * filteredBillYawRate * c
    local targetSpeed = math.sqrt(targetVx * targetVx + targetVy * targetVy)
    local targetYaw = billYaw
    if targetSpeed > 0.004 then
        targetYaw = atan2(targetVy, targetVx)
    end

    return {
        billSpeed = billSpeed,
        billYawRate = filteredBillYawRate,
        targetX = targetX,
        targetY = targetY,
        targetYaw = targetYaw,
        targetSpeed = targetSpeed,
    }
end

local function computeLqrControl(robotPos, robotYaw, ref, d)
    local dxTarget = ref.targetX - robotPos[1]
    local dyTarget = ref.targetY - robotPos[2]
    local c = math.cos(robotYaw)
    local s = math.sin(robotYaw)
    local eLong = c * dxTarget + s * dyTarget
    local eLat = -s * dxTarget + c * dyTarget
    local eYaw = wrapAngle(ref.targetYaw - robotYaw)

    local k = lqrCfg.K
    local deltaV = -(k[1][1] * eLong + k[1][2] * eLat + k[1][3] * eYaw)
    local deltaW = -(k[2][1] * eLong + k[2][2] * eLat + k[2][3] * eYaw)
    local vRef = clamp(ref.targetSpeed, 0, d.vMax or cfg.vMax)
    local wRef = clamp(ref.billYawRate, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)

    local v = vRef + deltaV
    local w = wRef + deltaW
    if math.abs(eLong) < (d.deadband or 0) and math.abs(eLat) < (d.deadband or 0) then
        if math.abs(v - vRef) < (d.commandDeadband or 0) then
            v = vRef
        end
    end

    if math.abs(eYaw) > 1.35 then
        v = 0
    elseif math.abs(eYaw) > 0.85 then
        v = clamp(v, -0.02, 0.10)
    end

    return clamp(v, d.vReverseMax or cfg.vReverseMax, d.vMax or cfg.vMax),
        clamp(w, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)
end

local function resetNmpcSequence()
    nmpcInitialized = false
    nmpcSeqV = {}
    nmpcSeqW = {}
end

local function initializeNmpcSequence()
    if nmpcInitialized then
        for i = 1, nmpcCfg.horizon - 1 do
            nmpcSeqV[i] = nmpcSeqV[i + 1] or nmpcSeqV[i] or actualV
            nmpcSeqW[i] = nmpcSeqW[i + 1] or nmpcSeqW[i] or actualW
        end
        nmpcSeqV[nmpcCfg.horizon] = nmpcSeqV[nmpcCfg.horizon - 1] or actualV
        nmpcSeqW[nmpcCfg.horizon] = nmpcSeqW[nmpcCfg.horizon - 1] or actualW
        return
    end

    for i = 1, nmpcCfg.horizon do
        nmpcSeqV[i] = actualV
        nmpcSeqW[i] = actualW
    end
    nmpcInitialized = true
end

local function nmpcCost(seqV, seqW, robotPos, robotYaw, billPos, billYaw, ref, d)
    local x = robotPos[1]
    local y = robotPos[2]
    local yaw = robotYaw
    local bx = billPos[1]
    local by = billPos[2]
    local byaw = billYaw
    local previousV = actualV
    local previousW = actualW
    local cost = 0

    for i = 1, nmpcCfg.horizon do
        local v = clamp(seqV[i] or 0, d.vReverseMax or cfg.vReverseMax, d.vMax or cfg.vMax)
        local w = clamp(seqW[i] or 0, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)
        local h = nmpcCfg.dt

        yaw = wrapAngle(yaw + w * h)
        x = x + v * math.cos(yaw) * h
        y = y + v * math.sin(yaw) * h

        byaw = wrapAngle(byaw + ref.billYawRate * h)
        bx = bx + ref.billSpeed * math.cos(byaw) * h
        by = by + ref.billSpeed * math.sin(byaw) * h

        local c = math.cos(byaw)
        local s = math.sin(byaw)
        local tx = bx - cfg.desiredDistance * c
        local ty = by - cfg.desiredDistance * s
        local dxBill = bx - x
        local dyBill = by - y
        local distance = math.sqrt(dxBill * dxBill + dyBill * dyBill)
        local eDistance = distance - cfg.desiredDistance
        local eTargetX = tx - x
        local eTargetY = ty - y
        local eHeading = wrapAngle(atan2(dyBill, dxBill) - yaw)

        local leftOmega = (v - 0.5 * cfg.trackWidth * w) / cfg.wheelRadius
        local rightOmega = (v + 0.5 * cfg.trackWidth * w) / cfg.wheelRadius
        local duV = v - previousV
        local duW = w - previousW
        local terminalScale = 1
        if i == nmpcCfg.horizon then
            terminalScale = nmpcCfg.terminal
        end

        cost = cost
            + terminalScale * nmpcCfg.qDistance * eDistance * eDistance
            + terminalScale * nmpcCfg.qTarget * (eTargetX * eTargetX + eTargetY * eTargetY)
            + nmpcCfg.qHeading * eHeading * eHeading
            + nmpcCfg.rV * v * v
            + nmpcCfg.rW * w * w
            + nmpcCfg.rWheel * (leftOmega * leftOmega + rightOmega * rightOmega)
            + nmpcCfg.sV * duV * duV
            + nmpcCfg.sW * duW * duW

        previousV = v
        previousW = w
    end

    return cost
end

local function computeNmpcControl(robotPos, robotYaw, billPos, billYaw, ref, d)
    initializeNmpcSequence()
    local bestCost = nmpcCost(nmpcSeqV, nmpcSeqW, robotPos, robotYaw, billPos, billYaw, ref, d)

    for pass = 1, nmpcCfg.iterations do
        local stepV = nmpcCfg.stepV[pass] or nmpcCfg.stepV[#nmpcCfg.stepV]
        local stepW = nmpcCfg.stepW[pass] or nmpcCfg.stepW[#nmpcCfg.stepW]

        for i = 1, nmpcCfg.horizon do
            local originalV = nmpcSeqV[i]
            local candidateV = originalV
            for _, sign in ipairs({1, -1}) do
                nmpcSeqV[i] = clamp(originalV + sign * stepV, d.vReverseMax or cfg.vReverseMax, d.vMax or cfg.vMax)
                local c = nmpcCost(nmpcSeqV, nmpcSeqW, robotPos, robotYaw, billPos, billYaw, ref, d)
                if c < bestCost then
                    bestCost = c
                    candidateV = nmpcSeqV[i]
                end
            end
            nmpcSeqV[i] = candidateV

            local originalW = nmpcSeqW[i]
            local candidateW = originalW
            for _, sign in ipairs({1, -1}) do
                nmpcSeqW[i] = clamp(originalW + sign * stepW, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)
                local c = nmpcCost(nmpcSeqV, nmpcSeqW, robotPos, robotYaw, billPos, billYaw, ref, d)
                if c < bestCost then
                    bestCost = c
                    candidateW = nmpcSeqW[i]
                end
            end
            nmpcSeqW[i] = candidateW
        end
    end

    return clamp(nmpcSeqV[1] or 0, d.vReverseMax or cfg.vReverseMax, d.vMax or cfg.vMax),
        clamp(nmpcSeqW[1] or 0, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)
end

local function publish(state, distance, error, heading, v, w, derivative)
    sim.setStringSignal('followerMode', mode)
    sim.setStringSignal('followerState', state)
    sim.setFloatSignal('followerDistance', distance or -1)
    sim.setFloatSignal('followerDistanceError', error or 0)
    sim.setFloatSignal('followerHeadingError', heading or 0)
    sim.setFloatSignal('followerIntegralError', integral)
    sim.setFloatSignal('followerDerivativeError', derivative or 0)
    sim.setFloatSignal('followerControlV', v or 0)
    sim.setFloatSignal('followerControlW', w or 0)
    sim.setInt32Signal('followerReady', 1)
end

local function logState(state, distance, error, v, w)
    local t = sim.getSimulationTime()
    if state ~= lastState or (t - lastLogT) >= cfg.logPeriod then
        sim.addLog(
            sim.verbosity_scriptinfos,
            string.format(
                'Follower %s state=%s distance=%.3f error=%.3f v=%.3f w=%.3f',
                mode,
                state,
                distance or -1,
                error or 0,
                v or 0,
                w or 0
            )
        )
        lastState = state
        lastLogT = t
    end
end

function sysCall_init()
    robot = safeGetObject('/PioneerP3DX')
    bill = safeGetObject('/Bill')
    leftMotor = safeGetObject('/PioneerP3DX/leftMotor')
    rightMotor = safeGetObject('/PioneerP3DX/rightMotor')

    mode = readMode()
    integral = 0
    lastError = 0
    lastErrorValid = false
    lastHeadingValid = false
    filteredDerivative = 0
    actualV = 0
    actualW = 0
    lastPowerV = 0
    lastPowerW = 0
    lastULeft = 0
    lastURight = 0
    energyJ = 0
    settledLatched = false
    lastBillYaw = 0
    lastBillYawValid = false
    filteredBillYawRate = 0
    resetNmpcSequence()
    lastT = sim.getSimulationTime()
    publishWheelPower(0, 0, 0)
    publish('INIT', -1, 0, 0, 0, 0, 0)
    sim.addLog(sim.verbosity_scriptinfos, 'Pioneer Bill follower ready: P, PI, PID, LQR and NMPC modes.')
end

function sysCall_actuation()
    if robot < 0 or bill < 0 or leftMotor < 0 or rightMotor < 0 then
        publish('ERROR_HANDLES', -1, 0, 0, 0, 0, 0)
        return
    end

    local newMode = readMode()
    if newMode ~= mode then
        mode = newMode
        integral = 0
        filteredDerivative = 0
        actualV = 0
        actualW = 0
        lastPowerV = 0
        lastPowerW = 0
        lastULeft = 0
        lastURight = 0
        energyJ = 0
        settledLatched = false
        lastBillYaw = 0
        lastBillYawValid = false
        filteredBillYawRate = 0
        resetNmpcSequence()
        lastError = 0
        lastErrorValid = false
        lastHeadingValid = false
        publishWheelPower(0, 0, 0)
    end

    local t = sim.getSimulationTime()
    local rawDt = t - lastT
    if rawDt <= 0.000001 then
        return
    end
    local dt = clamp(rawDt, 0.0, 0.12)
    lastT = t

    local robotPos = sim.getObjectPosition(robot)
    local billPos = sim.getObjectPosition(bill)
    local robotOri = sim.getObjectOrientation(robot)
    local billOri = sim.getObjectOrientation(bill)
    local dx = billPos[1] - robotPos[1]
    local dy = billPos[2] - robotPos[2]
    local distance = math.sqrt(dx * dx + dy * dy)
    local error = distance - cfg.desiredDistance
    local heading = wrapAngle(atan2(dy, dx) - robotOri[3])
    local ref = readBillReference(billPos, billOri[3], dt)

    if error * lastError < 0 then
        integral = integral * 0.35
    end
    if math.abs(heading) < 1.10 then
        integral = clamp(integral + error * dt, -cfg.integralLimit, cfg.integralLimit)
    else
        integral = integral * 0.985
    end

    local derivative = 0
    if lastErrorValid then
        derivative = clamp((error - lastError) / dt, -3.0, 3.0)
    end
    local g = gains[mode] or gains.P
    local d = drive[mode] or drive.P
    local derivativeAlpha = d.derivativeAlpha or cfg.derivativeAlpha
    filteredDerivative = derivativeAlpha * derivative + (1.0 - derivativeAlpha) * filteredDerivative
    lastError = error
    lastErrorValid = true

    local headingDerivative = 0
    if lastHeadingValid then
        headingDerivative = clamp(wrapAngle(heading - lastHeading) / dt, -4.0, 4.0)
    end
    lastHeading = heading
    lastHeadingValid = true

    local v = 0
    local w = 0
    if mode == 'LQR' then
        v, w = computeLqrControl(robotPos, robotOri[3], ref, d)
    elseif mode == 'NMPC' then
        v, w = computeNmpcControl(robotPos, robotOri[3], billPos, billOri[3], ref, d)
    else
        local rawV = g.kp * error + g.ki * integral + g.kd * filteredDerivative
        local forwardScale = clamp(math.cos(heading), 0, 1)
        v = clamp(rawV * forwardScale, d.vReverseMax or cfg.vReverseMax, d.vMax or cfg.vMax)
        if math.abs(heading) > 0.85 then
            v = clamp(rawV * 0.22, -0.02, 0.10)
        end
        if math.abs(heading) > 1.35 then
            v = 0
        end
        w = clamp((d.headingKp or cfg.headingKp) * heading + (d.headingKd or cfg.headingKd) * headingDerivative, -(d.wMax or cfg.wMax), d.wMax or cfg.wMax)
    end

    local state = 'FOLLOWING'
    local billStopped = sim.getInt32Signal('billStopped') == 1
    if billStopped and settledLatched and math.abs(error) < (d.settleExit or 0.12) and math.abs(heading) < 0.30 then
        v = 0
        w = 0
        actualV = 0
        actualW = 0
        state = 'SETTLED'
    elseif billStopped and math.abs(error) < (d.settleError or 0.08) and math.abs(heading) < 0.24 then
        settledLatched = true
        v = 0
        w = 0
        actualV = 0
        actualW = 0
        state = 'SETTLED'
    else
        settledLatched = false
    end

    if state ~= 'SETTLED' and math.abs(error) < 0.08 then
        state = 'TRACKING'
    end

    local response = d.accel or 5.0
    if math.abs(v) < math.abs(actualV) or (v * actualV) < 0 then
        response = d.brake or response
    end
    actualV = firstOrder(actualV, v, response, dt)
    actualW = firstOrder(actualW, w, d.turnAccel or response, dt)

    setWheelSpeeds(actualV, actualW)
    integrateKinematicBase(actualV, actualW, dt)
    publishWheelPower(actualV, actualW, dt)
    publish(state, distance, error, heading, actualV, actualW, filteredDerivative)
    logState(state, distance, error, actualV, actualW)
end

function sysCall_cleanup()
    if leftMotor >= 0 and rightMotor >= 0 then
        setWheelSpeeds(0, 0)
    end
    actualV = 0
    actualW = 0
    publishWheelPower(0, 0, 0)
    publish('STOPPED', -1, 0, 0, 0, 0, 0)
end
